### ISSUE TITLE
Error while installing the package via 'pip install'

### ISSUE THREAD

**Issue by ghost** [xolox/python-vcs-repo-mgr#2]
Hi, I'm getting an error trying to install this package. I'm using **Python 3.5.2**.  The error message is the following:

```
Collecting vcs-repo-mgr
  Using cached vcs-repo-mgr-0.32.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-h_jil8df/vcs-repo-mgr/setup.py", line 31, in <module>
        readme_text = open(readme_file, 'r').read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 13626: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-h_jil8df/vcs-repo-mgr/
```

Can you assist?
Thanks in advance!

**Comment by xolox** [comment]
Hi Silvino and thanks for the feedback! This should now be fixed, please try out version 0.32.1.
